"use client";
import { useRouter } from "next/navigation";

export const metadata = {
  title: "Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const router = useRouter();
  const token = localStorage.getItem("access_token");
  if (!token) {
    router.push("/login");
  }
  return <>{children}</>;
}
