"use client";

import { NextUIProvider } from "@nextui-org/system";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/ui/navbar";
import { usePathname, useRouter } from "next/navigation";
import { ToastContainer } from "react-toastify";
import { error, succuss, info } from "@/components/modals/notify";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Next Ether",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();
  const pathname = usePathname();
  const token = localStorage.getItem("access_token");
  const role = localStorage.getItem("role");
  if (!token) {
    if (pathname === "/wallet" || pathname === "/admin") {
      info("You have to login first!");
      router.push("/");
    }
  } else {
    if (pathname === "/admin" && role !== "admin") {
      info("Admin privilege needed");
      router.push("/");
    }
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <Navbar />
          {children}
          <ToastContainer />
        </NextUIProvider>
      </body>
    </html>
  );
}
